---
- name: make sure curl is installed
  yum: name=curl state=present

- name: download and install from inetrworx setup script
  shell: sh <((curl -sL interworx.com/inst.sh)) -l

- name: initialization step for interworx. setting email, password, and license
  shell: /home/interworx/bin/goiworx.pex --email {{ iworxadminemail }} --password {{ iworxadminpassword }} --key {{ iworxlicense }}
